{
  "formatVersion": "1.1",
  "component": {
    "group": "com.the.data.plugin",
    "module": "plugin",
    "version": "1.0.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.38.jar",
          "url": "plugin-1.0.38.jar",
          "size": 13409,
          "sha512": "2f4eae4585f23b3c6b93246947ac390af66d51829fc882cc6d1e1a41ba29a27a4b78fd42b3231b6806dceafbe02435dd8515b517fbf0359832a15ab1e45833bb",
          "sha256": "e0626195092ca1e1ffd50ad0a224a41cfc0e459f2910bbdcdcb5b25233134c5a",
          "sha1": "3104e68c790e769f81989eb6dcfeae5f2257318b",
          "md5": "63048a28e3845d59015c65120c58231a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.38.jar",
          "url": "plugin-1.0.38.jar",
          "size": 13409,
          "sha512": "2f4eae4585f23b3c6b93246947ac390af66d51829fc882cc6d1e1a41ba29a27a4b78fd42b3231b6806dceafbe02435dd8515b517fbf0359832a15ab1e45833bb",
          "sha256": "e0626195092ca1e1ffd50ad0a224a41cfc0e459f2910bbdcdcb5b25233134c5a",
          "sha1": "3104e68c790e769f81989eb6dcfeae5f2257318b",
          "md5": "63048a28e3845d59015c65120c58231a"
        }
      ]
    }
  ]
}
