{
  "formatVersion": "1.1",
  "component": {
    "group": "com.the.data.plugin",
    "module": "plugin",
    "version": "1.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.23.jar",
          "url": "plugin-1.0.23.jar",
          "size": 13802,
          "sha512": "d22e01785d3a1314904740cd098e2ece1087e75db9bff826945a3b96fdd71bf108881963034626115ef585fc37420b0f334271dd9922bb24a16b6fab19c385b2",
          "sha256": "d2921c3a4ebc57cf10fced1959890aac96ad90ba533b5bad5c3a3915e079e934",
          "sha1": "2e5131e7c5ad51705f4bda5e76e227988b9f1bda",
          "md5": "082b04e4c61fe1dbf442731241d806e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.23.jar",
          "url": "plugin-1.0.23.jar",
          "size": 13802,
          "sha512": "d22e01785d3a1314904740cd098e2ece1087e75db9bff826945a3b96fdd71bf108881963034626115ef585fc37420b0f334271dd9922bb24a16b6fab19c385b2",
          "sha256": "d2921c3a4ebc57cf10fced1959890aac96ad90ba533b5bad5c3a3915e079e934",
          "sha1": "2e5131e7c5ad51705f4bda5e76e227988b9f1bda",
          "md5": "082b04e4c61fe1dbf442731241d806e6"
        }
      ]
    }
  ]
}
