{
  "formatVersion": "1.1",
  "component": {
    "group": "com.the.data.plugin",
    "module": "plugin",
    "version": "1.0.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.35.jar",
          "url": "plugin-1.0.35.jar",
          "size": 13924,
          "sha512": "d0c309741ee2aa7a51cd529bfadb31c594b8189e5736fd88e0f663f31fcc0458bfa232c5e664c029299f5fbcfcca5fc8eb13c0326c6d6f62f680ce728a3279de",
          "sha256": "0e4c3fb66e2e9329edde79150051c71d607a43617748c115514ba58bbc32067b",
          "sha1": "df674c597592f35381ac4e382cae1a63759d2c45",
          "md5": "87f2835b045f8f63966af6930d0787a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.35.jar",
          "url": "plugin-1.0.35.jar",
          "size": 13924,
          "sha512": "d0c309741ee2aa7a51cd529bfadb31c594b8189e5736fd88e0f663f31fcc0458bfa232c5e664c029299f5fbcfcca5fc8eb13c0326c6d6f62f680ce728a3279de",
          "sha256": "0e4c3fb66e2e9329edde79150051c71d607a43617748c115514ba58bbc32067b",
          "sha1": "df674c597592f35381ac4e382cae1a63759d2c45",
          "md5": "87f2835b045f8f63966af6930d0787a8"
        }
      ]
    }
  ]
}
