{
  "formatVersion": "1.1",
  "component": {
    "group": "com.the.data.plugin",
    "module": "plugin",
    "version": "1.0.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.34.jar",
          "url": "plugin-1.0.34.jar",
          "size": 13963,
          "sha512": "d58a9f3280011aa3bf6db14a7f81048dbead07a1601d11c4ab49cd7114cc28f99110cb3ce13aa3117da1490e6c013edc20d1b8c0ea3e6335ae17ffb4840d390c",
          "sha256": "9e17d7d5b1091002cce98ac74f6161c593ab26972ccc288d7d3ae8493df796ec",
          "sha1": "151b128134d582f84a62a9bb4aa36de6de587b35",
          "md5": "8a70594f35757fff10407699b7a0031d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.34.jar",
          "url": "plugin-1.0.34.jar",
          "size": 13963,
          "sha512": "d58a9f3280011aa3bf6db14a7f81048dbead07a1601d11c4ab49cd7114cc28f99110cb3ce13aa3117da1490e6c013edc20d1b8c0ea3e6335ae17ffb4840d390c",
          "sha256": "9e17d7d5b1091002cce98ac74f6161c593ab26972ccc288d7d3ae8493df796ec",
          "sha1": "151b128134d582f84a62a9bb4aa36de6de587b35",
          "md5": "8a70594f35757fff10407699b7a0031d"
        }
      ]
    }
  ]
}
