{
  "formatVersion": "1.1",
  "component": {
    "group": "com.the.data.plugin",
    "module": "plugin",
    "version": "1.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.24.jar",
          "url": "plugin-1.0.24.jar",
          "size": 13810,
          "sha512": "8745677adc2319fef704fdcdcb5d6bd03ecb600cf659a56802bd780af18d52fff1fe94283847d4c0d9bf609d1f97397266575ed048a86a1ba578a6f875d42d3b",
          "sha256": "5ff8c7ef71df8bfa69153530fbec5f3d80a180d701c7d3152fe564fe80600999",
          "sha1": "7460cbf97caaccbdb0379bd2def8c39a7e852ab8",
          "md5": "3b5a24b305e987600fb6fefa97395813"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.24.jar",
          "url": "plugin-1.0.24.jar",
          "size": 13810,
          "sha512": "8745677adc2319fef704fdcdcb5d6bd03ecb600cf659a56802bd780af18d52fff1fe94283847d4c0d9bf609d1f97397266575ed048a86a1ba578a6f875d42d3b",
          "sha256": "5ff8c7ef71df8bfa69153530fbec5f3d80a180d701c7d3152fe564fe80600999",
          "sha1": "7460cbf97caaccbdb0379bd2def8c39a7e852ab8",
          "md5": "3b5a24b305e987600fb6fefa97395813"
        }
      ]
    }
  ]
}
