{
  "formatVersion": "1.1",
  "component": {
    "group": "com.the.data.plugin",
    "module": "plugin",
    "version": "1.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.28.jar",
          "url": "plugin-1.0.28.jar",
          "size": 13795,
          "sha512": "aaf91c29ff19b5eb933c960de2b751f431a1f4f0f94e7b898fd66033ed3d25d14717f4dc69437bef0d85c832a16f3461d3c7375fe0c9ec30bbffc1153f41d16a",
          "sha256": "e9cbc25a1125090a88fce72c337425a809ebbbfe64464cadd06aa56da49315dd",
          "sha1": "88768959a5d5432be25359e917bc376603f35d23",
          "md5": "bc5b037752c7f85f00d523904ebaf5a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.28.jar",
          "url": "plugin-1.0.28.jar",
          "size": 13795,
          "sha512": "aaf91c29ff19b5eb933c960de2b751f431a1f4f0f94e7b898fd66033ed3d25d14717f4dc69437bef0d85c832a16f3461d3c7375fe0c9ec30bbffc1153f41d16a",
          "sha256": "e9cbc25a1125090a88fce72c337425a809ebbbfe64464cadd06aa56da49315dd",
          "sha1": "88768959a5d5432be25359e917bc376603f35d23",
          "md5": "bc5b037752c7f85f00d523904ebaf5a7"
        }
      ]
    }
  ]
}
