{
  "formatVersion": "1.1",
  "component": {
    "group": "com.the.data.plugin",
    "module": "plugin",
    "version": "1.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.27.jar",
          "url": "plugin-1.0.27.jar",
          "size": 13803,
          "sha512": "584b47c15bd91c109bc68f0874b545fae60e39829d311b500f1df30f491bee126f93e1a6f88994e2e1335806a1aa2fab20a34cf8bf7824858578c9aad3b8a9ad",
          "sha256": "438f86d81289abdffb0f133ed07f1eb3ef14a4bf6c686b66fdfa110d90cb9b30",
          "sha1": "65e6048dc177cbe8c340a3a61d9072896ee0598b",
          "md5": "3eac38079552dd4735875c201e16a091"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.27.jar",
          "url": "plugin-1.0.27.jar",
          "size": 13803,
          "sha512": "584b47c15bd91c109bc68f0874b545fae60e39829d311b500f1df30f491bee126f93e1a6f88994e2e1335806a1aa2fab20a34cf8bf7824858578c9aad3b8a9ad",
          "sha256": "438f86d81289abdffb0f133ed07f1eb3ef14a4bf6c686b66fdfa110d90cb9b30",
          "sha1": "65e6048dc177cbe8c340a3a61d9072896ee0598b",
          "md5": "3eac38079552dd4735875c201e16a091"
        }
      ]
    }
  ]
}
