{
  "formatVersion": "1.1",
  "component": {
    "group": "Pulgin.plugin",
    "module": "thedataplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "thedataplugin-unspecified.jar",
          "url": "thedataplugin-unspecified.jar",
          "size": 13411,
          "sha512": "1c926f2973b5d7e0112059dcf5800b0ff4350c549553b7199695b1626fa22582355bff9c81effa9006183a48b2d21ecf34d0588797f3618cd8a8f9226af49948",
          "sha256": "93bbf93e66db08528a505553c90286f18d4d5ac65792657e0d0c8de9d5acca42",
          "sha1": "e795872de8d0ddff900c1bc414d0de7359db38b3",
          "md5": "ea9b7d06c6a71244e43b6960e7fca1c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "thedataplugin-unspecified.jar",
          "url": "thedataplugin-unspecified.jar",
          "size": 13411,
          "sha512": "1c926f2973b5d7e0112059dcf5800b0ff4350c549553b7199695b1626fa22582355bff9c81effa9006183a48b2d21ecf34d0588797f3618cd8a8f9226af49948",
          "sha256": "93bbf93e66db08528a505553c90286f18d4d5ac65792657e0d0c8de9d5acca42",
          "sha1": "e795872de8d0ddff900c1bc414d0de7359db38b3",
          "md5": "ea9b7d06c6a71244e43b6960e7fca1c0"
        }
      ]
    }
  ]
}
