{
  "formatVersion": "1.1",
  "component": {
    "group": "com.the.data.plugin",
    "module": "plugin",
    "version": "1.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.26.jar",
          "url": "plugin-1.0.26.jar",
          "size": 13804,
          "sha512": "2ac4f431cbc42ecd81b85f1fb8196e42244f14120bce42d3af89be22189d8f89152cc619eb38ddb58ff58c21f760f9cf1e3e2424b353848c6eca87ca00ee1972",
          "sha256": "a67179520b9ba7ac727ed8fe9c2c85b85ddbec5d92b032aa2b05257b928a2734",
          "sha1": "074a2598cb8ebd1f29c4e6fc3fd833a013110866",
          "md5": "2e982d8db13c96b251780e450acec104"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.26.jar",
          "url": "plugin-1.0.26.jar",
          "size": 13804,
          "sha512": "2ac4f431cbc42ecd81b85f1fb8196e42244f14120bce42d3af89be22189d8f89152cc619eb38ddb58ff58c21f760f9cf1e3e2424b353848c6eca87ca00ee1972",
          "sha256": "a67179520b9ba7ac727ed8fe9c2c85b85ddbec5d92b032aa2b05257b928a2734",
          "sha1": "074a2598cb8ebd1f29c4e6fc3fd833a013110866",
          "md5": "2e982d8db13c96b251780e450acec104"
        }
      ]
    }
  ]
}
