{
  "formatVersion": "1.1",
  "component": {
    "group": "com.the.data.plugin",
    "module": "plugin",
    "version": "1.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.36.jar",
          "url": "plugin-1.0.36.jar",
          "size": 13964,
          "sha512": "c9f44e06da4f3c531d2ebb21c0bbfa1c5312ae59380c2238c90e24118a76d890295ec5d8e23d4a90587f0ab320b18275a4de98ce95967bcb1f6c5853ecadf25b",
          "sha256": "1f2f946e85a64da9151fcb723f1e26b0ff857caf71181da9b7dbf916658375e8",
          "sha1": "f7286f3fbf9571b40cc63bee7dba14aae659558c",
          "md5": "a5af19048018f949ce4e1f953007d094"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.36.jar",
          "url": "plugin-1.0.36.jar",
          "size": 13964,
          "sha512": "c9f44e06da4f3c531d2ebb21c0bbfa1c5312ae59380c2238c90e24118a76d890295ec5d8e23d4a90587f0ab320b18275a4de98ce95967bcb1f6c5853ecadf25b",
          "sha256": "1f2f946e85a64da9151fcb723f1e26b0ff857caf71181da9b7dbf916658375e8",
          "sha1": "f7286f3fbf9571b40cc63bee7dba14aae659558c",
          "md5": "a5af19048018f949ce4e1f953007d094"
        }
      ]
    }
  ]
}
