{
  "formatVersion": "1.1",
  "component": {
    "group": "com.the.data.plugin",
    "module": "plugin",
    "version": "1.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.29.jar",
          "url": "plugin-1.0.29.jar",
          "size": 13895,
          "sha512": "b6b2bdd0b45752495d30986223cdf6cff3ae9270e845261e898b56ec604c183430b4b792ed3de16347c0c7edd5e6fb386f8044de4ec8e186ff824912b04db4cf",
          "sha256": "7db154ffa9d2158bd65524e9141fd5a569b0e1ba581f25917f179a12170d8985",
          "sha1": "f62cbc800f6452f1846f0761ce6018f41f866131",
          "md5": "a69d2a27276310fdec805dac6852eab8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.29.jar",
          "url": "plugin-1.0.29.jar",
          "size": 13895,
          "sha512": "b6b2bdd0b45752495d30986223cdf6cff3ae9270e845261e898b56ec604c183430b4b792ed3de16347c0c7edd5e6fb386f8044de4ec8e186ff824912b04db4cf",
          "sha256": "7db154ffa9d2158bd65524e9141fd5a569b0e1ba581f25917f179a12170d8985",
          "sha1": "f62cbc800f6452f1846f0761ce6018f41f866131",
          "md5": "a69d2a27276310fdec805dac6852eab8"
        }
      ]
    }
  ]
}
