{
  "formatVersion": "1.1",
  "component": {
    "group": "com.the.data.plugin",
    "module": "plugin",
    "version": "1.0.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.33.jar",
          "url": "plugin-1.0.33.jar",
          "size": 13962,
          "sha512": "b0c1235cf03a17f5ae4deb428b95757cb398c2fc45e509dbcf55d3806342486b0ce3ae77cb79f64981cd33243360fe9d1c9e4e2a3b8a647687f0ed637459d892",
          "sha256": "b76a257984ae29f55cf2878d197cf3ac1b272c9d78935d8f50459b4d04b8f8b3",
          "sha1": "259e175c97f8ff5faeac21528302a28f4abb20ab",
          "md5": "e8c8e70996b3607ce8d3045432267e6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.33.jar",
          "url": "plugin-1.0.33.jar",
          "size": 13962,
          "sha512": "b0c1235cf03a17f5ae4deb428b95757cb398c2fc45e509dbcf55d3806342486b0ce3ae77cb79f64981cd33243360fe9d1c9e4e2a3b8a647687f0ed637459d892",
          "sha256": "b76a257984ae29f55cf2878d197cf3ac1b272c9d78935d8f50459b4d04b8f8b3",
          "sha1": "259e175c97f8ff5faeac21528302a28f4abb20ab",
          "md5": "e8c8e70996b3607ce8d3045432267e6f"
        }
      ]
    }
  ]
}
