{
  "formatVersion": "1.1",
  "component": {
    "group": "com.the.data.plugin",
    "module": "plugin",
    "version": "1.0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.30.jar",
          "url": "plugin-1.0.30.jar",
          "size": 13944,
          "sha512": "1f609a37003024b94aeeb6c018fae3659643e5fd596e6f712bbf1ed3ac8295bf23a5b29f213e3f167cd978db7532d820927671e1fd509745953f5b2755ea7d00",
          "sha256": "5921de3465ab07f2e56fa5a6c04569a43a5596366ef237ec08982db4b21098ec",
          "sha1": "09ea94b889afa71a2df972bf84f86f079ed6d019",
          "md5": "88fac823219cd5527e05b803e4569096"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.30.jar",
          "url": "plugin-1.0.30.jar",
          "size": 13944,
          "sha512": "1f609a37003024b94aeeb6c018fae3659643e5fd596e6f712bbf1ed3ac8295bf23a5b29f213e3f167cd978db7532d820927671e1fd509745953f5b2755ea7d00",
          "sha256": "5921de3465ab07f2e56fa5a6c04569a43a5596366ef237ec08982db4b21098ec",
          "sha1": "09ea94b889afa71a2df972bf84f86f079ed6d019",
          "md5": "88fac823219cd5527e05b803e4569096"
        }
      ]
    }
  ]
}
