{
  "formatVersion": "1.1",
  "component": {
    "group": "com.the.data.plugin",
    "module": "plugin",
    "version": "1.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.22.jar",
          "url": "plugin-1.0.22.jar",
          "size": 13853,
          "sha512": "e496c8e27ee00a5debb217d5c2880cd2b77517b3bbb67ee01ace4bfcb87e545cd0941f88d73e402ad02910c7a93a4415c42606d4fe975d01eb6f71053095b39c",
          "sha256": "bd15b4fe63246e06532748c7a1ed322b80128ba58ec363827029ea509be690f4",
          "sha1": "cf26f9b79fb194c8eb7dc22af33026b0b7393e16",
          "md5": "9a0f19184ed027bcc1469bba87d17375"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.22.jar",
          "url": "plugin-1.0.22.jar",
          "size": 13853,
          "sha512": "e496c8e27ee00a5debb217d5c2880cd2b77517b3bbb67ee01ace4bfcb87e545cd0941f88d73e402ad02910c7a93a4415c42606d4fe975d01eb6f71053095b39c",
          "sha256": "bd15b4fe63246e06532748c7a1ed322b80128ba58ec363827029ea509be690f4",
          "sha1": "cf26f9b79fb194c8eb7dc22af33026b0b7393e16",
          "md5": "9a0f19184ed027bcc1469bba87d17375"
        }
      ]
    }
  ]
}
